### PR TITLE
adds ability to load extra fonts for PDF

### PR DESCRIPTION
**Pull request by rodnaph**
includes updated JAR file.

### CODE REVIEW

**Comment by develth** [comment]
is there an Example on how to use custom fonts?
I added the pathes as an array, but how can i use those fonts in e.g. the HTML?

**Comment by rodnaph** [comment]
@develth If the font paths are referenced correctly you should be able to use them in CSS like normal...

```
html {
  font-family: "My New Font";
}
```

**Comment by develth** [comment]
@rodnaph thanks. i already figured it out - had a typo in it. But it seems some properties are ignored like letter spacing. Even on a "default font" like Arial.

**Comment by rodnaph** [comment]
You mean some CSS doesn't work in general or just some properties on
included fonts? If you mean in general then yes it'll only be what is
supported by the flyingsaucer library this project wraps.

**Pull request merged**
